import type { Artigo } from './tipos'

export const artigos: Artigo[] = [
  {
    slug: 'internacao-voluntaria-involuntaria-compulsoria',
    titulo: 'Como funciona a internação voluntária, involuntária e compulsória',
    resumo: 'Entenda as diferenças legais e clínicas entre os tipos de internação, quando cada uma é indicada e quais são os direitos do paciente.',
    imagem: '/images/blog/internacao.jpg',
    tag: 'Internação',
    autor: 'Equipe Porta de Volta',
    dataPublicacao: '2026-04-10',
    tempoLeitura: '8 min',
    conteudo: [
      { tipo: 'intro', texto: 'Quando uma pessoa enfrenta dependência química grave, a internação pode ser a alternativa mais segura para iniciar o processo de recuperação. No Brasil, a Lei nº 10.216/2001 regulamenta os tipos de internação e garante direitos fundamentais ao paciente.' },
      { tipo: 'h2', texto: 'Internação Voluntária' },
      { tipo: 'paragrafo', texto: 'A internação voluntária ocorre quando o próprio paciente consente e assina o pedido de internação. É considerada a modalidade ideal, pois o engajamento do paciente no tratamento tende a ser maior. Segundo o Conselho Federal de Medicina, a adesão espontânea é um dos principais fatores preditivos de sucesso na recuperação.' },
      { tipo: 'paragrafo', texto: 'Nessa modalidade, o paciente tem o direito de solicitar alta a qualquer momento — mas a equipe médica pode avaliar se a saída representa risco à sua saúde. Caso isso ocorra, a internação pode ser convertida em involuntária, mediante notificação ao Ministério Público.' },
      { tipo: 'h2', texto: 'Internação Involuntária' },
      { tipo: 'paragrafo', texto: 'A internação involuntária é realizada sem o consentimento do paciente, a pedido de familiar ou responsável legal, e deve ser autorizada por um médico. É indicada quando a pessoa representa risco a si mesma ou a terceiros, ou quando está incapacitada de decidir por conta própria.' },
      { tipo: 'paragrafo', texto: 'A Lei nº 10.216/2001 determina que a internação involuntária seja comunicada ao Ministério Público Estadual em até 72 horas. A família deve manter acompanhamento próximo e o médico responsável deve reavaliar periodicamente a necessidade de manutenção.' },
      { tipo: 'destaque', texto: 'A internação involuntária não é punição — é um recurso de proteção quando a pessoa não tem condições de decidir por si mesma.' },
      { tipo: 'h2', texto: 'Internação Compulsória' },
      { tipo: 'paragrafo', texto: 'A internação compulsória é determinada exclusivamente por ordem judicial, geralmente a pedido do Ministério Público ou de familiares, após avaliação médica. É utilizada em casos extremos, quando há risco evidente e imediato à vida do paciente ou de terceiros.' },
      { tipo: 'h2', texto: 'Qual modalidade escolher?' },
      { tipo: 'paragrafo', texto: 'A escolha da modalidade deve sempre ser orientada por um profissional de saúde. Em geral, a sequência recomendada é: tentar primeiro a adesão voluntária, recorrer à internação involuntária quando há risco claro, e acionar a via judicial apenas em último caso.' },
      { tipo: 'fontes', itens: ['Lei nº 10.216/2001 — Lei da Reforma Psiquiátrica Brasileira', 'Conselho Federal de Medicina (CFM) — Resolução CFM nº 2.057/2013', 'Conselho Nacional de Justiça (CNJ) — Relatório sobre internações compulsórias', 'Organização Mundial da Saúde (OMS) — Mental Health Action Plan 2013–2030'] },
    ],
  },
  {
    slug: 'quanto-tempo-dura-tratamento',
    titulo: 'Quanto tempo dura o tratamento para dependência química?',
    resumo: 'A recuperação não tem prazo fixo. Entenda as fases do tratamento, o papel da desintoxicação e por que o acompanhamento contínuo faz toda a diferença.',
    imagem: '/images/blog/tratamento.jpg',
    tag: 'Tratamento',
    autor: 'Equipe Porta de Volta',
    dataPublicacao: '2026-04-15',
    tempoLeitura: '7 min',
    conteudo: [
      { tipo: 'intro', texto: 'Uma das perguntas mais comuns de famílias que buscam tratamento é: quanto tempo vai durar? A resposta honesta é: depende. Depende da substância, do tempo de uso, das condições físicas e psicológicas do paciente e do suporte familiar disponível.' },
      { tipo: 'h2', texto: 'Fase 1 — Desintoxicação (7 a 30 dias)' },
      { tipo: 'paragrafo', texto: 'A desintoxicação é a eliminação da substância do organismo, geralmente realizada com supervisão médica. Os sintomas de abstinência variam conforme a substância: no caso do álcool, podem incluir convulsões e delírio; no crack, agitação intensa e paranoia. O acompanhamento psiquiátrico nessa fase é fundamental.' },
      { tipo: 'h2', texto: 'Fase 2 — Reabilitação (30 a 90 dias)' },
      { tipo: 'paragrafo', texto: 'Após a desintoxicação, começa o trabalho terapêutico: psicoterapia individual e em grupo, terapia familiar, atividades ocupacionais e educação sobre a doença. O Instituto Nacional sobre Abuso de Drogas dos EUA (NIDA) recomenda um mínimo de 90 dias de tratamento para resultados consistentes.' },
      { tipo: 'destaque', texto: 'Pesquisas do NIDA mostram que pacientes que permanecem em tratamento por 90 dias ou mais têm taxas de recaída significativamente menores.' },
      { tipo: 'h2', texto: 'Fase 3 — Manutenção e reinserção (6 meses a 2 anos)' },
      { tipo: 'paragrafo', texto: 'A recuperação não termina com a alta da clínica. O acompanhamento ambulatorial, grupos de apoio como Narcóticos Anônimos e Alcoólicos Anônimos, e a terapia contínua são essenciais para prevenir recaídas.' },
      { tipo: 'h2', texto: 'Recaída não é fracasso' },
      { tipo: 'paragrafo', texto: 'A OMS classifica a dependência química como uma doença crônica com padrão recorrente. Recaídas fazem parte do processo para muitas pessoas e não significam que o tratamento falhou — significam que o plano terapêutico precisa ser revisado.' },
      { tipo: 'fontes', itens: ['National Institute on Drug Abuse (NIDA) — Principles of Drug Addiction Treatment, 4ª ed.', 'Organização Mundial da Saúde (OMS) — Global Status Report on Alcohol and Health 2022', 'ABEAD — Associação Brasileira de Estudos do Álcool e outras Drogas', 'Ministério da Saúde — A Política do Ministério da Saúde para Atenção Integral a Usuários de Álcool e outras Drogas'] },
    ],
  },
  {
    slug: 'sinais-familiar-precisa-ajuda',
    titulo: 'Sinais de que seu familiar precisa de ajuda profissional',
    resumo: 'Isolamento, mudanças de comportamento, faltas no trabalho. Aprenda a identificar os sinais de alerta e como agir com cuidado e sem confronto.',
    imagem: '/images/blog/familia.jpg',
    tag: 'Família',
    autor: 'Equipe Porta de Volta',
    dataPublicacao: '2026-04-20',
    tempoLeitura: '6 min',
    conteudo: [
      { tipo: 'intro', texto: 'Reconhecer que um familiar precisa de ajuda profissional é um dos momentos mais difíceis para uma família. A negação é um mecanismo comum que atrasa a busca por tratamento. Conhecer os sinais de alerta é o primeiro passo para agir com clareza e sem culpa.' },
      { tipo: 'h2', texto: 'Sinais comportamentais' },
      { tipo: 'paragrafo', texto: 'Mudanças abruptas de humor, irritabilidade excessiva, isolamento social, abandono de hobbies. A pessoa começa a priorizar o uso da substância acima de tudo — trabalho, família, saúde. Mentiras frequentes e comportamento secretivo são sinais clássicos de dependência em estágio avançado.' },
      { tipo: 'h2', texto: 'Sinais físicos' },
      { tipo: 'paragrafo', texto: 'Perda ou ganho de peso significativo em curto período, olhos avermelhados ou dilatados, tremores, sudorese excessiva, descuido com higiene pessoal. A presença de marcas no corpo ou hematomas inexplicáveis também podem indicar uso de substâncias.' },
      { tipo: 'destaque', texto: 'A negação é parte da doença — tanto do dependente quanto da família. Reconhecer isso não é fraqueza; é o começo da solução.' },
      { tipo: 'h2', texto: 'Sinais sociais e profissionais' },
      { tipo: 'paragrafo', texto: 'Faltas frequentes no trabalho ou na escola, queda no desempenho, dívidas inexplicáveis, desaparecimento de objetos ou dinheiro em casa, afastamento de amigos antigos e aproximação de novos grupos desconhecidos pela família.' },
      { tipo: 'h2', texto: 'Como agir sem piorar a situação' },
      { tipo: 'paragrafo', texto: 'Evite confrontos agressivos ou ultimatos sem suporte profissional. A Entrevista Motivacional mostra que abordagens empáticas e sem julgamento são mais eficazes do que pressão e ameaças. Busque orientação antes de agir — nossa equipe pode ajudar a planejar a melhor abordagem.' },
      { tipo: 'fontes', itens: ['Organização Mundial da Saúde (OMS) — ICD-11: Disorders due to substance use', 'NIDA — Signs of Drug Use and Addiction', 'Miller, W.R. & Rollnick, S. — Motivational Interviewing, 3ª ed. (Guilford Press)', 'Ministério da Saúde — Saúde Mental no SUS: Os Centros de Atenção Psicossocial'] },
    ],
  },
  {
    slug: 'como-apoiar-dependente-sem-se-destruir',
    titulo: 'Como apoiar um dependente químico sem se destruir',
    resumo: 'Quem cuida também precisa de cuidado. Veja como estabelecer limites saudáveis, preservar sua saúde mental e ajudar de forma efetiva.',
    imagem: '/images/blog/apoio.jpg',
    tag: 'Família',
    autor: 'Equipe Porta de Volta',
    dataPublicacao: '2026-04-25',
    tempoLeitura: '7 min',
    conteudo: [
      { tipo: 'intro', texto: 'Conviver com um dependente químico é emocionalmente exaustivo. Familiares frequentemente desenvolvem codependência — um padrão em que a vida gira inteiramente em torno do dependente, negligenciando as próprias necessidades. Cuidar de quem você ama não pode custar a sua saúde.' },
      { tipo: 'h2', texto: 'O que é codependência?' },
      { tipo: 'paragrafo', texto: 'Codependência é um padrão relacional em que o familiar assume responsabilidade excessiva pelo comportamento do dependente, encobre consequências do uso e coloca as necessidades do outro consistentemente acima das suas. A codependência pode retardar a busca por tratamento.' },
      { tipo: 'h2', texto: 'Estabeleça limites com clareza e afeto' },
      { tipo: 'paragrafo', texto: 'Limites não são punições — são proteções. Exemplos: não mentir para cobrir ausências do familiar, não fornecer dinheiro que possa ser usado para comprar substâncias, não aceitar comportamentos violentos. O grupo Al-Anon oferece suporte gratuito a familiares de dependentes de álcool.' },
      { tipo: 'destaque', texto: 'Você não causou a dependência do seu familiar. Você não pode curá-la sozinho. Mas pode apoiar a recuperação — cuidando também de você.' },
      { tipo: 'h2', texto: 'Cuide da sua saúde mental' },
      { tipo: 'paragrafo', texto: 'Busque terapia individual. Participe de grupos de apoio para familiares. Mantenha sua rede social ativa. Pesquisas mostram que familiares que recebem suporte psicológico têm papel significativamente mais positivo no processo de recuperação do dependente.' },
      { tipo: 'fontes', itens: ['Al-Anon Family Groups — al-anon.org.br', 'Nar-Anon Brasil — naranon.org.br', 'Journal of Substance Abuse Treatment — Family involvement in addiction treatment', 'Beattie, M. — Codependent No More (Hazelden Publishing)'] },
    ],
  },
  {
    slug: 'o-que-e-entrevista-motivacional',
    titulo: 'O que é Entrevista Motivacional e como ela ajuda na recuperação',
    resumo: 'Uma das abordagens mais eficazes no tratamento da dependência. Entenda como funciona e por que respeitar o ritmo do paciente é fundamental.',
    imagem: '/images/blog/metodologia.jpg',
    tag: 'Metodologia',
    autor: 'Equipe Porta de Volta',
    dataPublicacao: '2026-04-28',
    tempoLeitura: '6 min',
    conteudo: [
      { tipo: 'intro', texto: 'A Entrevista Motivacional (EM) é uma abordagem terapêutica desenvolvida pelos psicólogos William Miller e Stephen Rollnick na década de 1980. Baseada em empatia, escuta ativa e respeito pela autonomia do paciente, é hoje uma das técnicas mais validadas cientificamente no tratamento de dependência química.' },
      { tipo: 'h2', texto: 'Como funciona na prática' },
      { tipo: 'paragrafo', texto: 'Em vez de confrontar o paciente, o terapeuta explora a ambivalência — aquele estado em que a pessoa sente ao mesmo tempo o desejo de mudar e a resistência a isso. Por meio de perguntas abertas e escuta reflexiva, o profissional ajuda a fortalecer a motivação interna para a mudança.' },
      { tipo: 'h2', texto: 'Por que é mais eficaz do que a confrontação' },
      { tipo: 'paragrafo', texto: 'Abordagens confrontadoras frequentemente aumentam a resistência do dependente e retardam a busca por tratamento. Meta-análises publicadas no Journal of Consulting and Clinical Psychology mostram que a EM reduz o uso de substâncias e aumenta a retenção no tratamento.' },
      { tipo: 'destaque', texto: 'A mudança duradoura vem de dentro. A Entrevista Motivacional cria as condições para que o paciente encontre suas próprias razões para se recuperar.' },
      { tipo: 'h2', texto: 'Quando é utilizada' },
      { tipo: 'paragrafo', texto: 'A EM é especialmente eficaz nas fases iniciais do tratamento, quando o paciente ainda não decidiu buscar ajuda. Também é usada em consultas ambulatoriais e aconselhamento familiar. Nossa equipe utiliza princípios da EM em todos os atendimentos iniciais.' },
      { tipo: 'fontes', itens: ['Miller, W.R. & Rollnick, S. — Motivational Interviewing: Helping People Change, 3ª ed.', 'Journal of Consulting and Clinical Psychology — Meta-analysis of Motivational Interviewing', 'NIDA — Evidence-Based Approaches to Drug Addiction Treatment', 'Sociedade Brasileira de Psicologia — Entrevista Motivacional na prática clínica'] },
    ],
  },
  {
    slug: 'diferenca-clinica-comunidade-terapeutica',
    titulo: 'Diferença entre clínica de reabilitação e comunidade terapêutica',
    resumo: 'Duas abordagens distintas, cada uma com seus benefícios. Saiba qual é a mais indicada para cada perfil e como escolher com segurança.',
    imagem: '/images/blog/recuperacao.jpg',
    tag: 'Tratamento',
    autor: 'Equipe Porta de Volta',
    dataPublicacao: '2026-05-01',
    tempoLeitura: '7 min',
    conteudo: [
      { tipo: 'intro', texto: 'Clínica de reabilitação e comunidade terapêutica são frequentemente confundidas, mas representam abordagens distintas com características, públicos e metodologias diferentes. Conhecer essas diferenças é essencial para escolher o caminho mais adequado.' },
      { tipo: 'h2', texto: 'Clínica de Reabilitação' },
      { tipo: 'paragrafo', texto: 'As clínicas de reabilitação são estabelecimentos de saúde regulamentados pela ANVISA e pelo Conselho Federal de Medicina. Contam com equipe multidisciplinar — psiquiatras, psicólogos, enfermeiros, assistentes sociais e terapeutas — e oferecem tratamento clínico estruturado, incluindo desintoxicação médica supervisionada.' },
      { tipo: 'h2', texto: 'Comunidade Terapêutica' },
      { tipo: 'paragrafo', texto: 'As comunidades terapêuticas são residências de longa permanência — geralmente de 6 a 18 meses — baseadas em princípios de convivência, espiritualidade e mutualidade. São regulamentadas pela ANVISA (RDC nº 29/2011) e pelo CONAD. O foco é na reinserção social e no desenvolvimento de valores.' },
      { tipo: 'destaque', texto: 'Não existe opção melhor ou pior — existe a opção mais adequada para cada perfil, momento e necessidade clínica.' },
      { tipo: 'h2', texto: 'Como escolher com segurança' },
      { tipo: 'paragrafo', texto: 'Verifique sempre se o estabelecimento está regularizado pela ANVISA. Desconfie de locais que prometem cura rápida ou que não apresentam equipe técnica qualificada. O Cadastro Nacional de Estabelecimentos de Saúde (CNES) permite consultar clínicas registradas em todo o Brasil.' },
      { tipo: 'h2', texto: 'Quando cada um é indicado' },
      { tipo: 'paragrafo', texto: 'Clínica de reabilitação: casos com abstinência grave, comorbidades psiquiátricas, histórico de convulsões ou overdose. Comunidade terapêutica: casos onde o ambiente social é fator de risco central. Em muitos casos, o ideal é iniciar na clínica e continuar na comunidade.' },
      { tipo: 'fontes', itens: ['ANVISA — RDC nº 29/2011 — Regulamentação de Comunidades Terapêuticas', 'CONAD — Resolução nº 1/2015', 'Cadastro Nacional de Estabelecimentos de Saúde (CNES) — cnes.datasus.gov.br', 'CFM — Resolução CFM nº 2.057/2013', 'SENAD — Secretaria Nacional de Políticas sobre Drogas'] },
    ],
  },
]
